// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env['DATABASE_URL'] ||
  process.env['DATABASE_PRIVATE_URL'] ||
  process.env['POSTGRES_URL'] ||
  process.env['POSTGRES_PRISMA_URL'];

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx ts-node prisma/seed.ts',
  },
  datasource: {
    url: databaseUrl,
  },
});

